# Generated by Django 5.2.7 on 2025-10-07 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='e.g., Python, SQL, AWS. Required before applying.', max_length=255, null=True),
        ),
    ]
